---
- name: Check if Fathom is already installed.
  stat:
    path: /usr/local/bin/fathom
  register: fathom_bin

- name: Ensure temporary directory for Fathom exists.
  file:
    path: /tmp/fathom
    state: directory
  when: >
    not fathom_bin.stat.exists
    or fathom_force_update

- name: Download Fathom.
  unarchive:
    src: "{{ fathom_binary_url }}"
    dest: /tmp/fathom
    remote_src: true
  register: archive_contents
  when: >
    not fathom_bin.stat.exists
    or fathom_force_update

- name: Copy Fathom binary into place.
  copy:
    src: /tmp/fathom/fathom
    dest: /usr/local/bin/fathom
    mode: 0755
    remote_src: true
  notify: restart fathom
  when: >
    not fathom_bin.stat.exists
    or fathom_force_update
