---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: geerlingguy.fathom

  post_tasks:
    - name: Ensure Fathom is responding on the specified port.
      uri:
        url: "http://127.0.0.1:{{ fathom_http_port }}"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 1
