---
- name: Converge
  hosts: all
  become: true

  vars:
    fathom_http_port: '9999'
    nginx_remove_default_vhost: true
    nginx_vhosts:
      - listen: "80 default_server"
        server_name: "_"
        state: "present"
        filename: "fathom.conf"
        extra_parameters: |
          location / {
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $remote_addr;
              proxy_set_header Host $host;
              proxy_pass http://127.0.0.1:{{ fathom_http_port }};
          }

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: geerlingguy.repo-epel
    - role: geerlingguy.fathom
    - role: geerlingguy.nginx

  post_tasks:
    - name: Ensure Fathom is responding through Nginx.
      uri:
        url: "http://127.0.0.1/"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 1
